spring.application.name=barber

# Datos de conexión
spring.datasource.url=jdbc:postgresql://localhost:5432/barberia
spring.datasource.username=izan
spring.datasource.password=izan
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT
jwt.secret=TU_SECRETO_MUY_LARGO_Y_SEGURO_!cambiaEsto!
jwt.expiration-ms=3600000  # 1 hora